apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    name: redis
    function: broker
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30081


